Use clippy (#635)
Co-authored-by: Nam Se Hyun <3580430+namse@users.noreply.github.com>

diff --git a/.github/actions/cargo-test/action.yml b/.github/actions/cargo-test/action.yml
--- a/.github/actions/cargo-test/action.yml
+++ b/.github/actions/cargo-test/action.yml
@@ -45,3 +45,14 @@ runs:
         else
             echo "Good. Cargo.lock is up to date (or it ignored by gitignore)"
         fi
+
+    - name: Did you forget run cargo clippy
+      shell: bash
+      run: |
+        cargo clippy --manifest-path ${{ inputs.path }}/Cargo.toml -- -D warnings
+        if [ $? -ne 0 ]; then
+            echo "::error::Clippy failed. Please check code with 'cargo clippy' before push"
+            exit 1
+        else
+            echo "Good. Clippy passed"
+        fi
diff --git a/.github/actions/namui-test/action.yml b/.github/actions/namui-test/action.yml
--- a/.github/actions/namui-test/action.yml
+++ b/.github/actions/namui-test/action.yml
@@ -21,7 +21,8 @@ runs:
 
     - name: Test
       shell: bash
-      run: time namui test ${{ inputs.target }} -m ${{ inputs.path }}/Cargo.toml
+      working-directory: ${{ inputs.path }}
+      run: time namui test ${{ inputs.target }}
 
     - name: Did you push Cargo.lock
       shell: bash
@@ -36,7 +37,8 @@ runs:
 
     - name: Fmt
       shell: bash
-      run: cargo fmt --manifest-path ${{ inputs.path }}/Cargo.toml
+      working-directory: ${{ inputs.path }}
+      run: cargo fmt
 
     - name: Did you forget run fmt
       shell: bash
@@ -47,4 +49,17 @@ runs:
             exit 1
         else
             echo "Good. Cargo.lock is up to date (or it ignored by gitignore)"
+        fi
+
+    - name: Did you forget run cargo clippy
+      shell: bash
+      working-directory: ${{ inputs.path }}
+      run: |
+        # NOTE: `cargo clippy` seems not respect .cargo/config.toml when use --manifest-path.
+        cargo clippy -- -D warnings
+        if [ $? -ne 0 ]; then
+            echo "::error::Clippy failed. Please check code with 'cargo clippy' before push"
+            exit 1
+        else
+            echo "Good. Clippy passed"
         fi
