Save and load ecs app (#443)

diff --git a/.github/actions/namui-test/action.yml b/.github/actions/namui-test/action.yml
--- a/.github/actions/namui-test/action.yml
+++ b/.github/actions/namui-test/action.yml
@@ -18,21 +18,6 @@ runs:
           **/target/
         key: ${{ runner.os }}-cargo-${{ inputs.path }}-${{ inputs.target }}-${{ hashFiles('${{ inputs.path }}/Cargo.lock') }}
 
-    - name: Fmt
-      shell: bash
-      run: cargo fmt --manifest-path ${{ inputs.path }}/Cargo.toml
-
-    - name: Did you forget run fmt
-      shell: bash
-      run: |
-        if [[ $(git diff --name-only) ]]; then
-            echo "::error::File change detected. Please run 'cargo fmt' before push"
-            echo  "::error::$(git diff --name-only)"
-            exit 1
-        else
-            echo "Good. Cargo.lock is up to date (or it ignored by gitignore)"
-        fi
-
     - name: Test
       shell: bash
       run: time namui test ${{ inputs.target }} -m ${{ inputs.path }}/Cargo.toml
@@ -42,6 +27,21 @@ runs:
       run: |
         if [[ $(git diff --name-only) ]]; then
             echo "::error::File change detected. If it's Cargo.lock, you should add it into git"
+            echo  "::error::$(git diff --name-only)"
+            exit 1
+        else
+            echo "Good. Cargo.lock is up to date (or it ignored by gitignore)"
+        fi
+
+    - name: Fmt
+      shell: bash
+      run: cargo fmt --manifest-path ${{ inputs.path }}/Cargo.toml
+
+    - name: Did you forget run fmt
+      shell: bash
+      run: |
+        if [[ $(git diff --name-only) ]]; then
+            echo "::error::File change detected. Please run 'cargo fmt' before push"
             echo  "::error::$(git diff --name-only)"
             exit 1
         else
