Check Cargo.lock in CI (#189)
* Check Cargo.lock in CI

* Fix it

* Update action.yml

* Update Cargo.lock

diff --git a/.github/actions/namui-test/action.yml b/.github/actions/namui-test/action.yml
--- a/.github/actions/namui-test/action.yml
+++ b/.github/actions/namui-test/action.yml
@@ -19,3 +19,14 @@ runs:
     - name: Test
       shell: bash
       run: time namui test ${{ inputs.target }} -m ${{ inputs.path }}/Cargo.toml
+
+    - name: Did you push Cargo.lock
+      shell: bash
+      run: |
+        if [[ $(git diff --name-only) ]]; then
+            echo "::error::File change detected. If it's Cargo.lock, you should add it into git"
+            echo  "::error::$(git diff --name-only)"
+            exit 1
+        else
+            echo "Good. Cargo.lock is up to date (or it ignored by gitignore)"
+        fi
