post-test

diff --git a/.github/workflows/all.yml b/.github/workflows/all.yml
--- a/.github/workflows/all.yml
+++ b/.github/workflows/all.yml
@@ -51,3 +51,20 @@ jobs:
               echo "::error::$(git diff --name-only)"
               exit 1
           fi
+
+  post-test:
+    if: always()
+    runs-on: ubuntu-latest
+    needs:
+      - run-commands
+    steps:
+      - run: |
+          echo ${{ join(needs.*.result, ',') }}
+          any_test_failed=${{ contains(join(needs.*.result, ','), 'failure') }}
+          echo $any_test_failed
+          if [[ $any_test_failed == "true" ]]; then
+              echo "::error::There are failed job"
+              exit 1
+          else
+              echo "Good. No test failed"
+          fi
