Let go~

diff --git a/.github/workflows/all.yml b/.github/workflows/all.yml
--- a/.github/workflows/all.yml
+++ b/.github/workflows/all.yml
@@ -12,6 +12,7 @@ env:
   SCCACHE_GHA_ENABLED: true
   RUSTC_WRAPPER: sccache
   CARGO_INCREMENTAL: 0
+  RUSTFLAGS: -D warnings
 
 jobs:
   list-projects:
@@ -21,14 +22,8 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - uses: mozilla-actions/sccache-action@v0.0.3
-      - uses: ./.github/actions/rustup-update
-
-      - uses: katyo/publish-crates@v2
-        with:
-          path: "for-all-projects"
-          registry-token: ${{ secrets.CARGO_API_TOKEN }}
-
-      - uses: ./.github/actions/publish-and-install-for-all-projects
+      - run: rustup update
+      - uses: ./.github/actions/build-for-all-projects
 
       - name: Output list of project directories
         id: project-dirs
@@ -43,9 +38,14 @@ jobs:
         dir: ${{ fromJSON(needs.list-projects.outputs.project-dirs) }}
     steps:
       - uses: actions/checkout@v3
-      - uses: mozilla-actions/sccache-action@v0.0.3
-      - uses: ./.github/actions/rustup-update
-      - uses: ./.github/actions/publish-and-install-for-all-projects
+      - uses: ./.github/actions/init-test-job
+      - uses: ./.github/actions/build-for-all-projects
 
-      - name: Matrix => (${{ matrix.dir }}
-        run: echo "Running in ${{ matrix.dir }}"
+      - run: |
+          for-all-projects run --only ${{ matrix.dir }} --check --fmt --fix --clippy --test
+
+          if [[ $(git diff --name-only) ]]; then
+              echo "::error::File change detected. Please check."
+              echo "::error::$(git diff --name-only)"
+              exit 1
+          fi
