Test

diff --git a/.github/workflows/oioi-agent-image-push.yml b/.github/workflows/oioi-agent-image-push.yml
--- a/.github/workflows/oioi-agent-image-push.yml
+++ b/.github/workflows/oioi-agent-image-push.yml
@@ -145,6 +145,28 @@ jobs:
 
           echo $DNS_NAME
 
-          curl --fail http://$DNS_NAME
+          retries=0
+          MAX_RETRIES=30
+          RETRY_INTERVAL=10
+          SUCCESS=false
+
+          while [ $retries -lt $MAX_RETRIES ]; do
+            response=$(curl -s -o /dev/null -w "%{http_code}" http://$DNS_NAME)
+            
+            if [ $response -eq 200 ]; then
+              echo "HTTP Endpoint check successful."
+              SUCCESS=true
+              break
+            else
+              echo "Retrying in $RETRY_INTERVAL seconds..."
+              sleep $RETRY_INTERVAL
+              retries=$((retries+1))
+            fi
+          done
+
+          if [ "$SUCCESS" = false ] ; then
+            echo "HTTP Endpoint check failed."
+            exit 1
+          fi
 
           aws cloudformation delete-stack --stack-name $STACK_NAME
