.github/workflows/test-and-fmt-clippy.yml

diff --git a/.github/workflows/test-and-fmt-clippy.yml b/.github/workflows/test-and-fmt-clippy.yml
--- a/.github/workflows/test-and-fmt-clippy.yml
+++ b/.github/workflows/test-and-fmt-clippy.yml
@@ -1,4 +1,4 @@
-name: namui-macos-host-aarch64-apple-darwin
+name: test-and-fmt-clippy
 on:
   pull_request:
 
@@ -6,7 +6,7 @@ permissions:
   contents: write
 
 concurrency:
-  group: ${{ github.ref }}-namui-macos-host-aarch64-apple-darwin
+  group: ${{ github.ref }}-test-and-fmt-clippy
   cancel-in-progress: true
 
 env:
@@ -30,8 +30,6 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: true
-          token: ${{ secrets.PAT_CARGO_LOCK_UPDATE }}
-          persist-credentials: false
 
       - name: Set up cargo
         run: |
@@ -60,13 +58,37 @@ jobs:
         with:
           prefix: ${{ matrix.os }}-${{ matrix.target }}
 
+      - name: Create workspace
+        run: |
+          cargo run --manifest-path github-actions-tools/workspace-maker/Cargo.toml ${{ matrix.target }}
+
       - name: Run commands
         run: |
           cargo test
 
-  code-validation:
+  post-test:
+    if: always()
+    runs-on: ubuntu-latest
+    needs:
+      - test
+    steps:
+      - run: |
+          echo ${{ join(needs.*.result, ',') }}
+          any_test_failed=${{ contains(join(needs.*.result, ','), 'failure') }}
+          echo $any_test_failed
+          if [[ $any_test_failed == "true" ]]; then
+              echo "::error::There are failed job"
+              exit 1
+          else
+              echo "Good. No test failed"
+          fi
+
+  fmt-clippy:
+    needs:
+      - post-test
     strategy:
       max-parallel: 1
+      fail-fast: false
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
         include:
@@ -79,16 +101,28 @@ jobs:
           - os: windows-latest
             target: x86_64-pc-windows-msvc
     runs-on: ${{ matrix.os }}
+    permissions:
+      contents: write
+      actions: read
     steps:
-      # 첫번째 작업하는 애는 checkout 해서 코드 가져오고
-      # 작업 다 하고 upload-artifact 로 target 제외하고 올려.
-      # 그것을 모든 애들에 대해 반복하고
-      # 변경사항 있으면 커밋하고 푸시해.
-      - uses: actions/checkout@v4
+      - name: Check if code artifact exists
+        id: check-code
+        uses: softwareforgood/check-artifact-v4-existence@v0
+        with:
+          name: code-${{ matrix.target }}
+
+      - name: Download code if exists
+        if: steps.check-code.outputs.exists == 'true'
+        uses: actions/download-artifact@v4
+        with:
+          name: code-${{ matrix.target }}
+          path: .
+
+      - name: Checkout if first job
+        if: steps.check-code.outputs.exists == 'false'
+        uses: actions/checkout@v4
         with:
           submodules: true
-          token: ${{ secrets.PAT_CARGO_LOCK_UPDATE }}
-          persist-credentials: false
 
       - name: Set up cargo
         run: |
@@ -117,6 +151,38 @@ jobs:
         with:
           prefix: ${{ matrix.os }}-${{ matrix.target }}
 
-      - name: Run commands
+      - name: Create workspace Cargo.toml
         run: |
-          cargo test
+          cargo run --manifest-path github-actions-tools/workspace-maker/Cargo.toml ${{ matrix.target }}
+
+      - run: cargo fmt --all
+
+      - run: cargo clippy --target ${{ matrix.target }} --tests --fix --allow-dirty
+
+      - name: Upload code for next job
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: code-${{ matrix.target }}-${{ github.run_id }}
+          path: |
+            .
+            !target
+          overwrite: true
+
+post-test-and-fmt-clippy:
+  if: always()
+  runs-on: ubuntu-latest
+  needs:
+    - test
+    - fmt-clippy
+  steps:
+    - run: |
+        echo ${{ join(needs.*.result, ',') }}
+        any_test_failed=${{ contains(join(needs.*.result, ','), 'failure') }}
+        echo $any_test_failed
+        if [[ $any_test_failed == "true" ]]; then
+            echo "::error::There are failed job"
+            exit 1
+        else
+            echo "Good. No test failed"
+        fi
